#!/bin/bash

# Dependency Update Skill
# Automatically checks for outdated dependencies and creates a PR with updates

set -e

echo "=== Dependency Update Skill ==="
echo "Checking for outdated dependencies..."

# Configuration
BRANCH_NAME="chore/dependency-updates-$(date +%Y%m%d)"
COMMIT_MESSAGE="chore: update dependencies"
PR_TITLE="chore: update dependencies"
PR_BODY="Automated dependency updates generated by the dependency-update skill."

# Check required tools
if ! command -v python3 &> /dev/null; then
    echo "ERROR: python3 is required but not installed."
    exit 1
fi

if ! command -v pip &> /dev/null; then
    echo "ERROR: pip is required but not installed."
    exit 1
fi

# Check if we're in a git repo
if ! git rev-parse --is-inside-work-tree &> /dev/null; then
    echo "ERROR: Not inside a git repository."
    exit 1
fi

# Store original branch
ORIGINAL_BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch: $ORIGINAL_BRANCH"

# Check for pyproject.toml or requirements files
HAS_PYPROJECT=false
HAS_REQUIREMENTS=false

if [ -f "pyproject.toml" ]; then
    HAS_PYPROJECT=true
    echo "Found pyproject.toml"
fi

if [ -f "requirements.txt" ]; then
    HAS_REQUIREMENTS=true
    echo "Found requirements.txt"
fi

if [ "$HAS_PYPROJECT" = false ] && [ "$HAS_REQUIREMENTS" = false ]; then
    echo "ERROR: No pyproject.toml or requirements.txt found."
    exit 1
fi

# Install pip-outdated or use pip list --outdated
echo ""
echo "--- Checking for outdated packages ---"
OUTDATED_OUTPUT=$(pip list --outdated --format=json 2>/dev/null || echo "[]")

if [ "$OUTDATED_OUTPUT" = "[]" ] || [ -z "$OUTDATED_OUTPUT" ]; then
    echo "All dependencies are up to date. Nothing to do."
    exit 0
fi

echo "Outdated packages found:"
echo "$OUTDATED_OUTPUT" | python3 -c "
import json, sys
packages = json.load(sys.stdin)
for pkg in packages:
    print(f\"  {pkg['name']}: {pkg['version']} -> {pkg['latest_version']}\")
"

PACKAGE_COUNT=$(echo "$OUTDATED_OUTPUT" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))")
echo ""
echo "Total outdated packages: $PACKAGE_COUNT"

# Create a new branch for the updates
echo ""
echo "--- Creating update branch ---"
git checkout -b "$BRANCH_NAME" 2>/dev/null || {
    echo "Branch $BRANCH_NAME already exists, switching to it."
    git checkout "$BRANCH_NAME"
}

# Update dependencies based on project type
if [ "$HAS_PYPROJECT" = true ]; then
    echo ""
    echo "--- Updating dependencies in pyproject.toml ---"

    # Check if uv is available for faster updates
    if command -v uv &> /dev/null; then
        echo "Using uv to update dependencies..."
        uv lock --upgrade 2>/dev/null || echo "Warning: uv lock upgrade failed, continuing..."
    else
        echo "Using pip to update dependencies..."
        # Update each outdated package
        echo "$OUTDATED_OUTPUT" | python3 -c "
import json, sys, subprocess
packages = json.load(sys.stdin)
for pkg in packages:
    name = pkg['name']
    latest = pkg['latest_version']
    print(f'Updating {name} to {latest}...')
    result = subprocess.run(['pip', 'install', f'{name}=={latest}'], capture_output=True, text=True)
    if result.returncode != 0:
        print(f'Warning: Failed to update {name}: {result.stderr}')
"
    fi
fi

if [ "$HAS_REQUIREMENTS" = true ]; then
    echo ""
    echo "--- Updating requirements.txt ---"
    # Update requirements.txt with latest versions
    echo "$OUTDATED_OUTPUT" | python3 -c "
import json, sys, re

packages = json.load(sys.stdin)
update_map = {pkg['name'].lower(): pkg['latest_version'] for pkg in packages}

with open('requirements.txt', 'r') as f:
    lines = f.readlines()

updated_lines = []
for line in lines:
    stripped = line.strip()
    if stripped and not stripped.startswith('#'):
        # Extract package name
        match = re.match(r'^([a-zA-Z0-9_\-\.]+)', stripped)
        if match:
            pkg_name = match.group(1).lower()
            if pkg_name in update_map:
                new_version = update_map[pkg_name]
                # Replace version specifier
                new_line = re.sub(r'([=<>!~]+)[\d\.\*]+', f'=={new_version}', stripped)
                if new_line == stripped:
                    new_line = f'{stripped}=={new_version}'
                updated_lines.append(new_line + '\n')
                print(f'Updated {pkg_name} -> {new_version}')
                continue
    updated_lines.append(line)

with open('requirements.txt', 'w') as f:
    f.writelines(updated_lines)
"
fi

# Check if there are any changes to commit
if git diff --quiet && git diff --staged --quiet; then
    echo ""
    echo "No file changes detected after updates. Cleaning up..."
    git checkout "$ORIGINAL_BRANCH"
    git branch -D "$BRANCH_NAME" 2>/dev/null || true
    exit 0
fi

# Commit the changes
echo ""
echo "--- Committing changes ---"
git add -A
git commit -m "$COMMIT_MESSAGE"

# Push the branch
echo ""
echo "--- Pushing branch ---"
git push origin "$BRANCH_NAME" 2>/dev/null || {
    echo "Warning: Could not push branch. You may need to push manually."
    echo "  git push origin $BRANCH_NAME"
}

# Create PR if gh CLI is available
if command -v gh &> /dev/null; then
    echo ""
    echo "--- Creating Pull Request ---"
    FULL_PR_BODY="$PR_BODY\n\n### Updated Packages\n"
    PACKAGES_LIST=$(echo "$OUTDATED_OUTPUT" | python3 -c "
import json, sys
packages = json.load(sys.stdin)
for pkg in packages:
    print(f\"- **{pkg['name']}**: {pkg['version']} → {pkg['latest_version']}\")
")
    FULL_PR_BODY="$FULL_PR_BODY\n$PACKAGES_LIST"

    gh pr create \
        --title "$PR_TITLE" \
        --body "$FULL_PR_BODY" \
        --base "$ORIGINAL_BRANCH" \
        --head "$BRANCH_NAME" \
        --label "dependencies" 2>/dev/null || {
        echo "Warning: Could not create PR automatically."
        echo "Please create a PR from branch: $BRANCH_NAME"
    }
else
    echo ""
    echo "gh CLI not found. Please create a PR manually from branch: $BRANCH_NAME"
fi

echo ""
echo "=== Dependency update complete ==="
echo "Branch: $BRANCH_NAME"
echo "Updated $PACKAGE_COUNT package(s)"
